### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by MartinRGB** [wirecube/android_additive_animations#1]
Error:Unable to find method 'org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by davidganster** [comment]
Hi,

are you using AS 3.0? Did you update the gradle wrapper?

I just cloned the repo and the gradle sync worked for me (AS 2.3, Gradle 2.4) out of the box - but I got an error similar to yours when using `distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip` in the gradle-wrapper.properties file. 

I'll check out what the problem with the 3.3 gradle wrapper is sometime tonight.

**Comment by MartinRGB** [comment]
Thanks!
I'‘m with `gradle-3.3-all.zip`  & AS 2.3.3

in `build.gradle`,I update these:
```
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
```

**Comment by davidganster** [comment]
I just pushed a version with updated dependencies that works for me with gradle 3.3 and AS 2.3.3.

Would you mind trying it out and telling me if it works?

**Comment by MartinRGB** [comment]
It works,and I see smooth animation,thanks for your work!
