### ISSUE TITLE
Move away from jcenter

### ISSUE THREAD

**Issue by robbysmeticapps** [wirecube/android_additive_animations#17]
Recently JFrog announced they'll be sunsetting the jcenter registry: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

It looks like Maven Central is their recommended alternative https://search.maven.org/

**Comment by davidganster** [comment]
Hi, 

I'm aware that this is happening soon, but haven't found the time to actually migrate yet.
I hope to have this done soon, and will update the readme and this ticket once the migration is done!

**Comment by davidganster** [comment]
Hi again, 

I've migrated all versions starting from 1.1.3 to MavenCentral.

Cheers!
