### ISSUE TITLE
superfluous?

### ISSUE THREAD

**Issue by tenSunFree** [wirecube/android_additive_animations#3]
This seems to be superfluous
![2017-08-10_172056](https://user-images.githubusercontent.com/23090085/29164006-b52c5422-7df0-11e7-84cc-1af3b33009cd.jpg)

because
![2017-08-10_172414](https://user-images.githubusercontent.com/23090085/29164076-ee250fbc-7df0-11e7-8b98-1067c5b6473e.jpg)

**Comment by davidganster** [comment]
You're right, this is a leftover from an older version of the demo. 
I'll improve the demos soon - some of them aren't even functional in the non-additive mode at the moment.
