### ISSUE TITLE
effect?

### ISSUE THREAD

**Issue by tenSunFree** [wirecube/android_additive_animations#5]
Do not understand the effect of this is what?
![2017-08-12_221649](https://user-images.githubusercontent.com/23090085/29241442-a0a89eb2-7fac-11e7-860e-4e009119eeff.jpg)

**Comment by davidganster** [comment]
This is simply a showcase of how to cancel a specific animation on a view (in this case, rotation).
When you tap the screen in this demo, you will see that the view stops rotating, but all of the other animations keep running normally.
This also cancels all animations queued with `thenWithDelay()`.
