### ISSUE TITLE
Annoying `AdditiveAnimator` constructor with Kotlin

### ISSUE THREAD

**Issue by ScottPierce** [wirecube/android_additive_animations#6]
**Problem:**
Kotlin requires that type information be provided. i.e. the following code has an error.
```Kotlin
AdditiveAnimator()
```

Instead, it has to be used like this:
```Kotlin
AdditiveAnimator<AdditiveAnimator<*>>()
```

It's quite ugly and annoying.

**Short Term Solution:**
Please provide static methods that duplicate the constructor arguments.
```Kotlin
AdditiveAnimator.create()
AdditiveAnimator.create(300L)
```

**Long Term Solution:**
I don't understand the library well enough to recommend a good long-term solution, but ideally the API would be reconsidered with Kotlin in mind.

**Comment by ScottPierce** [comment]
Found another really annoying side-effect of the generic types on `AdditiveAnimator` in Kotlin. It makes extension functions difficult as well:

```Kotlin
  fun <T : AdditiveAnimator<T>> AdditiveAnimator<T>.visibleAlpha(isVisible: Boolean): AdditiveAnimator<T> {
    val endAlpha = if (isVisible) 1f else 0f
    return alpha(endAlpha)
  }
```

Kotlin errors out when you try to use this function, taking issue with the recursive types.

I've had to work around it by using:
```Kotlin
  fun <T : AdditiveAnimator<*>> AdditiveAnimator<T>.visibleAlpha(isVisible: Boolean): AdditiveAnimator<T> {
    val endAlpha = if (isVisible) 1f else 0f
    @Suppress("UNCHECKED_CAST")
    return alpha(endAlpha) as AdditiveAnimator<T>
  }
```

**Comment by davidganster** [comment]
Hi,

I will add the static creation methods you suggested, but I'm having no problem using the `AdditiveAnimator.animate()` methods in Kotlin.

I don't really know Kotlin very well (I only just installed AS 3.0 after I read your comment), but I came up with a few solutions to the function extension problem:

First, you can provide a subclass which instantiates the generic type.
Second, you can simply omit the generic specification and use `AdditiveAnimator<*>`.

Let me know if these approaches seem usable to you:

```Kotlin
// subclass specifies generic type
class AdditiveAnimatorSubclass : AdditiveAnimator<AdditiveAnimatorSubclass> {
    constructor(view: View) : super(view)

    // can simply return subclass
    fun visibleAlpha(visible: Boolean) : AdditiveAnimatorSubclass {
        return alpha(if(visible) 1f else 0f)
    }
}

// generic extension function
fun AdditiveAnimator<*>.visibleAlpha(isVisible: Boolean): AdditiveAnimator<*> {
    val endAlpha = if (isVisible) 1f else 0f
    return alpha(endAlpha)
}

// subclass extension function doesn't require generics
fun AdditiveAnimatorSubclass.xy(x: Float, y: Float): AdditiveAnimatorSubclass {
    return x(x).y(y)
}

class KotlinTestFragment : Fragment() {
    override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val root = inflater?.inflate(R.layout.fragment_tap_to_move_demo, container, false)!!
        val animatedView = root.findViewById(R.id.animated_view)!!
        root.setOnTouchListener({ _, motionEvent ->
            AdditiveAnimatorSubclass(animatedView).xy(motionEvent.x, motionEvent.y).visibleAlpha(true).start()
            // this works fine as well:
//            AdditiveAnimator.animate(animatedView).x(motionEvent.x).y(motionEvent.y).visibleAlpha(true).start()
            true
        })
        return root
    }
}
```

I also pushed these changes to the [/wirecube/android_additive_animations/tree/kotlin](https://github.com/wirecube/android_additive_animations/tree/kotlin) branch, if you'd like to try it out yourself.

**Comment by davidganster** [comment]
@ScottPierce did you have a chance to try out the code sample?

**Comment by ScottPierce** [comment]
not yet. I removed this animation library from our code base, and I think
subclassing the animation will theoretically fix the issues I pointed out
earlier. I hadn't realized that was the way it was intended to be used.

**Comment by ScottPierce** [comment]
Extending the base animation seems to be working well enough for the time being. Did you want me to keep this open to track the creation of the above mentioned static methods, or should this just be closed?

**Comment by davidganster** [comment]
I wanted to wait until I merged the `animate_objects` branch, which has the improved construction methods, but got sidetracked working on performance improvements.
I'll finally merge this on the weekend, and close this issue once I do. 

Thanks for reminding me!

**Comment by davidganster** [comment]
Hi, I just merged the `animate_objects` branch which removes the generics from `AdditiveAnimator`. This should remove the need for subclassing and make working with Kotlin easier!
